- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Run Docker Container
      docker_container:
        name: my_container
        image: rajni644/project:1
        state: started
        ports:
          - "8084:8091"  # Map port 8084 on host to port 8091 in the container
